package com.example.easyquery.dto;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.math.BigDecimal;
import java.util.List;

import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.example.easyquery.entity.Book }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@Data
public class BookInput {


    private String name;
    private Integer edition;
    private BigDecimal price;
    private Long storeId;


}
