package com.example.easyquery.dto;


import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;

import java.math.BigDecimal;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.example.easyquery.entity.Book }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: response
 */
@Data
public class BookDTO {


    private Long id;
    private String name;
    private Integer edition;
    private BigDecimal price;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private InternalStore store;


    /**
     * {@link com.example.easyquery.entity.BookStore }
     */
    @Data
    public static class InternalStore {

        private Long id;
        private String name;
        private String website;


    }

}
